namespace RadialLauncher.Services
{
    public static partial class ShortcutCatalog
    {
        private static readonly ShortcutDefinition[] All = new ShortcutDefinition[]
        {
            // ==== 系统 ====
            new("win-d", "系统", "System", "显示桌面 / 最小化所有窗口", "Show desktop / Minimize all windows", "Win+D"),
            new("win-e", "系统", "System", "打开文件资源管理器", "Open File Explorer", "Win+E"),
            new("win-i", "系统", "System", "打开“设置”应用", "Open the Settings app", "Win+I"),
            new("win-r", "系统", "System", "打开“运行”对话框", "Open the Run dialog", "Win+R"),
            new("win-s", "系统", "System", "打开搜索", "Open Search", "Win+S"),
            new("win-q", "系统", "System", "用旧版入口打开搜索", "Open Search with the legacy shortcut", "Win+Q"),
            new("win-a", "系统", "System", "打开快速设置面板", "Open Quick Settings", "Win+A"),
            new("win-n", "系统", "System", "打开通知中心与日历", "Open Notification Center and calendar", "Win+N"),
            new("win-w", "系统", "System", "打开小组件面板", "Open the Widgets panel", "Win+W"),
            new("win-v", "系统", "System", "打开剪贴板历史记录", "Open clipboard history", "Win+V"),
            new("win-period", "系统", "System", "打开表情符号面板", "Open the emoji panel", "Win+."),
            new("win-semicolon", "系统", "System", "打开表情符号与符号面板", "Open the emoji and symbols panel", "Win+;"),
            new("win-h", "系统", "System", "启动语音输入", "Start voice typing", "Win+H"),
            new("win-c", "系统", "System", "打开 Copilot 或 Teams 聊天", "Open Copilot or Teams chat", "Win+C"),
            new("win-k", "系统", "System", "打开“投放”连接面板", "Open the Cast and Connect panel", "Win+K"),
            new("win-f", "系统", "System", "打开反馈中心", "Open Feedback Hub", "Win+F"),
            new("win-f1", "系统", "System", "打开 Windows 帮助", "Open Windows help", "Win+F1"),
            new("win-pause", "系统", "System", "打开系统属性页面", "Open the System properties page", "Win+Pause"),
            new("win-ctrl-f", "系统", "System", "搜索网络上的计算机", "Search for computers on the network", "Win+Ctrl+F"),
            new("win-ctrl-q", "系统", "System", "打开快速助手", "Open Quick Assist", "Win+Ctrl+Q"),
            new("win-comma", "系统", "System", "临时查看桌面", "Peek at the desktop", "Win+,"),

            // ==== 窗口 ====
            new("alt-tab", "窗口", "Window", "切换应用窗口", "Switch between open windows", "Alt+Tab"),
            new("alt-shift-tab", "窗口", "Window", "反向切换应用窗口", "Switch windows in reverse order", "Alt+Shift+Tab"),
            new("ctrl-alt-tab", "窗口", "Window", "打开常驻的应用切换器", "Open the persistent window switcher", "Ctrl+Alt+Tab"),
            new("alt-esc", "窗口", "Window", "按打开顺序循环切换窗口", "Cycle through windows in opening order", "Alt+Esc"),
            new("win-up", "窗口", "Window", "最大化当前窗口", "Maximize the active window", "Win+Up"),
            new("win-down", "窗口", "Window", "最小化或还原当前窗口", "Minimize or restore the active window", "Win+Down"),
            new("win-left", "窗口", "Window", "将窗口贴靠到屏幕左侧", "Snap the window to the left", "Win+Left"),
            new("win-right", "窗口", "Window", "将窗口贴靠到屏幕右侧", "Snap the window to the right", "Win+Right"),
            new("win-home", "窗口", "Window", "最小化除当前窗口外的所有窗口", "Minimize every window except the active one", "Win+Home"),
            new("win-shift-up", "窗口", "Window", "把窗口拉伸到屏幕上下边缘", "Stretch the window to the top and bottom edges", "Win+Shift+Up"),
            new("win-shift-down", "窗口", "Window", "还原窗口的垂直尺寸", "Restore the window's vertical size", "Win+Shift+Down"),
            new("win-shift-left", "窗口", "Window", "把窗口移到左侧显示器", "Move the window to the left monitor", "Win+Shift+Left"),
            new("win-shift-right", "窗口", "Window", "把窗口移到右侧显示器", "Move the window to the right monitor", "Win+Shift+Right"),
            new("win-m", "窗口", "Window", "最小化所有窗口", "Minimize all windows", "Win+M"),
            new("win-shift-m", "窗口", "Window", "还原最小化的窗口", "Restore minimized windows", "Win+Shift+M"),
            new("win-z", "窗口", "Window", "打开贴靠布局", "Open Snap Layouts", "Win+Z"),
            new("alt-f4", "窗口", "Window", "关闭当前窗口或应用", "Close the active window or app", "Alt+F4"),
            new("ctrl-f4", "窗口", "Window", "关闭当前文档或子窗口", "Close the active document or child window", "Ctrl+F4"),

            // ==== 虚拟桌面 ====
            new("win-tab", "虚拟桌面", "Virtual Desktops", "打开任务视图", "Open Task View", "Win+Tab"),
            new("win-ctrl-d", "虚拟桌面", "Virtual Desktops", "新建虚拟桌面", "Create a new virtual desktop", "Win+Ctrl+D"),
            new("win-ctrl-left", "虚拟桌面", "Virtual Desktops", "切换到左侧虚拟桌面", "Switch to the virtual desktop on the left", "Win+Ctrl+Left"),
            new("win-ctrl-right", "虚拟桌面", "Virtual Desktops", "切换到右侧虚拟桌面", "Switch to the virtual desktop on the right", "Win+Ctrl+Right"),
            new("win-ctrl-f4", "虚拟桌面", "Virtual Desktops", "关闭当前虚拟桌面", "Close the current virtual desktop", "Win+Ctrl+F4"),

            // ==== 文件资源管理器 ====
            new("explorer-ctrl-n", "文件资源管理器", "File Explorer", "打开新的资源管理器窗口", "Open a new File Explorer window", "Ctrl+N"),
            new("explorer-ctrl-w", "文件资源管理器", "File Explorer", "关闭当前资源管理器窗口", "Close the active File Explorer window", "Ctrl+W"),
            new("explorer-ctrl-shift-n", "文件资源管理器", "File Explorer", "新建文件夹", "Create a new folder", "Ctrl+Shift+N"),
            new("explorer-ctrl-shift-e", "文件资源管理器", "File Explorer", "展开到当前文件夹", "Expand the folder tree to the current folder", "Ctrl+Shift+E"),
            new("alt-up", "文件资源管理器", "File Explorer", "返回上一级文件夹", "Go up one folder level", "Alt+Up"),
            new("explorer-alt-left", "文件资源管理器", "File Explorer", "后退到上一个位置", "Go back to the previous location", "Alt+Left"),
            new("explorer-alt-right", "文件资源管理器", "File Explorer", "前进到下一个位置", "Go forward to the next location", "Alt+Right"),
            new("explorer-alt-d", "文件资源管理器", "File Explorer", "选中地址栏", "Focus the address bar", "Alt+D"),
            new("alt-enter", "文件资源管理器", "File Explorer", "打开所选项目的属性", "Open the properties of the selected item", "Alt+Enter"),
            new("f2", "文件资源管理器", "File Explorer", "重命名所选项目", "Rename the selected item", "F2"),
            new("explorer-f3", "文件资源管理器", "File Explorer", "在资源管理器中搜索文件", "Search for files in File Explorer", "F3"),
            new("explorer-f4", "文件资源管理器", "File Explorer", "选中地址栏列表", "Focus the address bar list", "F4"),
            new("explorer-f5", "文件资源管理器", "File Explorer", "刷新当前窗口", "Refresh the current window", "F5"),
            new("f6", "文件资源管理器", "File Explorer", "在窗口各窗格之间循环切换焦点", "Cycle focus between the window panes", "F6"),
            new("explorer-f11", "文件资源管理器", "File Explorer", "全屏显示资源管理器", "Toggle full screen in File Explorer", "F11"),
            new("explorer-ctrl-e", "文件资源管理器", "File Explorer", "选中搜索框", "Focus the search box", "Ctrl+E"),
            new("explorer-ctrl-f", "文件资源管理器", "File Explorer", "搜索当前文件夹", "Search the current folder", "Ctrl+F"),
            new("ctrl-shift-1", "文件资源管理器", "File Explorer", "切换为超大图标视图", "Switch to extra large icons view", "Ctrl+Shift+1"),
            new("ctrl-shift-2", "文件资源管理器", "File Explorer", "切换为大图标视图", "Switch to large icons view", "Ctrl+Shift+2"),
            new("ctrl-shift-3", "文件资源管理器", "File Explorer", "切换为中等图标视图", "Switch to medium icons view", "Ctrl+Shift+3"),
            new("ctrl-shift-4", "文件资源管理器", "File Explorer", "切换为小图标视图", "Switch to small icons view", "Ctrl+Shift+4"),
            new("ctrl-shift-5", "文件资源管理器", "File Explorer", "切换为列表视图", "Switch to list view", "Ctrl+Shift+5"),
            new("ctrl-shift-6", "文件资源管理器", "File Explorer", "切换为详细信息视图", "Switch to details view", "Ctrl+Shift+6"),
            new("ctrl-shift-7", "文件资源管理器", "File Explorer", "切换为平铺视图", "Switch to tiles view", "Ctrl+Shift+7"),
            new("ctrl-shift-8", "文件资源管理器", "File Explorer", "切换为内容视图", "Switch to content view", "Ctrl+Shift+8"),
            new("shift-delete", "文件资源管理器", "File Explorer", "永久删除所选项目", "Permanently delete the selected item", "Shift+Delete"),

            // ==== 任务栏 ====
            new("win-t", "任务栏", "Taskbar", "循环切换任务栏上的应用", "Cycle through the apps on the taskbar", "Win+T"),
            new("win-b", "任务栏", "Taskbar", "把焦点移到通知区域", "Move focus to the notification area", "Win+B"),
            new("win-1", "任务栏", "Taskbar", "打开或切换到任务栏上第 1 个固定应用", "Open or switch to the 1st pinned taskbar app", "Win+1"),
            new("win-2", "任务栏", "Taskbar", "打开或切换到任务栏上第 2 个固定应用", "Open or switch to the 2nd pinned taskbar app", "Win+2"),
            new("win-3", "任务栏", "Taskbar", "打开或切换到任务栏上第 3 个固定应用", "Open or switch to the 3rd pinned taskbar app", "Win+3"),
            new("win-4", "任务栏", "Taskbar", "打开或切换到任务栏上第 4 个固定应用", "Open or switch to the 4th pinned taskbar app", "Win+4"),
            new("win-5", "任务栏", "Taskbar", "打开或切换到任务栏上第 5 个固定应用", "Open or switch to the 5th pinned taskbar app", "Win+5"),
            new("win-6", "任务栏", "Taskbar", "打开或切换到任务栏上第 6 个固定应用", "Open or switch to the 6th pinned taskbar app", "Win+6"),
            new("win-7", "任务栏", "Taskbar", "打开或切换到任务栏上第 7 个固定应用", "Open or switch to the 7th pinned taskbar app", "Win+7"),
            new("win-8", "任务栏", "Taskbar", "打开或切换到任务栏上第 8 个固定应用", "Open or switch to the 8th pinned taskbar app", "Win+8"),
            new("win-9", "任务栏", "Taskbar", "打开或切换到任务栏上第 9 个固定应用", "Open or switch to the 9th pinned taskbar app", "Win+9"),
            new("win-0", "任务栏", "Taskbar", "打开或切换到任务栏上第 10 个固定应用", "Open or switch to the 10th pinned taskbar app", "Win+0"),

            // ==== 辅助功能 ====
            new("win-u", "辅助功能", "Accessibility", "打开辅助功能设置", "Open Accessibility settings", "Win+U"),
            new("win-enter", "辅助功能", "Accessibility", "启动或关闭讲述人", "Turn Narrator on or off", "Win+Enter"),
            new("win-ctrl-enter", "辅助功能", "Accessibility", "启动讲述人", "Start Narrator", "Win+Ctrl+Enter"),
            new("win-ctrl-n", "辅助功能", "Accessibility", "打开讲述人设置", "Open Narrator settings", "Win+Ctrl+N"),
            new("win-esc", "辅助功能", "Accessibility", "关闭放大镜", "Close Magnifier", "Win+Esc"),
            new("alt-shift-printscreen", "辅助功能", "Accessibility", "开启或关闭高对比度", "Turn high contrast on or off", "Alt+Shift+PrintScreen"),
            new("win-ctrl-o", "辅助功能", "Accessibility", "打开屏幕键盘", "Open the On-Screen Keyboard", "Win+Ctrl+O"),
            new("win-ctrl-c", "辅助功能", "Accessibility", "开启或关闭颜色滤镜", "Turn color filters on or off", "Win+Ctrl+C"),

            // ==== 命令提示符与终端 ====
            new("terminal-ctrl-shift-t", "命令提示符与终端", "Terminal", "新建终端选项卡", "Open a new terminal tab", "Ctrl+Shift+T"),
            new("terminal-ctrl-shift-w", "命令提示符与终端", "Terminal", "关闭当前终端选项卡", "Close the current terminal tab", "Ctrl+Shift+W"),
            new("terminal-ctrl-shift-n", "命令提示符与终端", "Terminal", "新建终端窗口", "Open a new terminal window", "Ctrl+Shift+N"),
            new("terminal-ctrl-shift-c", "命令提示符与终端", "Terminal", "复制选中的终端文本", "Copy the selected terminal text", "Ctrl+Shift+C"),
            new("terminal-ctrl-shift-v", "命令提示符与终端", "Terminal", "粘贴到终端", "Paste into the terminal", "Ctrl+Shift+V"),
            new("terminal-ctrl-shift-f", "命令提示符与终端", "Terminal", "在终端中查找", "Find in the terminal", "Ctrl+Shift+F"),
            new("terminal-ctrl-shift-p", "命令提示符与终端", "Terminal", "打开终端命令面板", "Open the terminal command palette", "Ctrl+Shift+P"),
            new("terminal-ctrl-shift-space", "命令提示符与终端", "Terminal", "打开新选项卡下拉菜单", "Open the new tab dropdown menu", "Ctrl+Shift+Space"),
            new("terminal-ctrl-tab", "命令提示符与终端", "Terminal", "切换到下一个终端选项卡", "Switch to the next terminal tab", "Ctrl+Tab"),
            new("terminal-ctrl-shift-tab", "命令提示符与终端", "Terminal", "切换到上一个终端选项卡", "Switch to the previous terminal tab", "Ctrl+Shift+Tab"),
            new("terminal-ctrl-c", "命令提示符与终端", "Terminal", "中断当前正在运行的命令", "Interrupt the currently running command", "Ctrl+C"),
            new("terminal-ctrl-v", "命令提示符与终端", "Terminal", "粘贴（旧版控制台）", "Paste in the legacy console", "Ctrl+V"),
            new("terminal-f1", "命令提示符与终端", "Terminal", "逐字符重放上一条命令", "Replay the previous command one character at a time", "F1"),
            new("terminal-f2", "命令提示符与终端", "Terminal", "把上一条命令复制到指定字符", "Copy the previous command up to a given character", "F2"),
            new("terminal-f3", "命令提示符与终端", "Terminal", "重复上一条命令", "Repeat the previous command", "F3"),
            new("terminal-f4", "命令提示符与终端", "Terminal", "删除到指定字符", "Delete up to a specified character", "F4"),
            new("terminal-f5", "命令提示符与终端", "Terminal", "向前翻阅命令历史记录", "Step forward through the command history", "F5"),
            new("terminal-f6", "命令提示符与终端", "Terminal", "插入文件结束符", "Insert the end-of-file character", "F6"),
            new("terminal-f7", "命令提示符与终端", "Terminal", "显示命令历史记录", "Show the command history", "F7"),
            new("terminal-f8", "命令提示符与终端", "Terminal", "搜索命令历史记录", "Search the command history", "F8"),
            new("terminal-f9", "命令提示符与终端", "Terminal", "按编号选择历史命令", "Select a history command by number", "F9"),
            new("alt-f7", "命令提示符与终端", "Terminal", "清除命令历史记录", "Clear the command history", "Alt+F7"),
            new("terminal-esc", "命令提示符与终端", "Terminal", "清除当前命令行", "Clear the current command line", "Esc"),
            new("terminal-ctrl-home", "命令提示符与终端", "Terminal", "删除光标之前的所有文本", "Delete all text before the cursor", "Ctrl+Home"),
            new("terminal-ctrl-end", "命令提示符与终端", "Terminal", "删除光标之后的所有文本", "Delete all text after the cursor", "Ctrl+End"),
            new("terminal-tab", "命令提示符与终端", "Terminal", "自动补全文件或文件夹名", "Auto-complete a file or folder name", "Tab"),

            // ==== 浏览器 ====
            new("ctrl-t", "浏览器", "Browser", "新建标签页", "Open a new tab", "Ctrl+T"),
            new("browser-ctrl-w", "浏览器", "Browser", "关闭当前标签页", "Close the current tab", "Ctrl+W"),
            new("browser-ctrl-shift-t", "浏览器", "Browser", "重新打开最近关闭的标签页", "Reopen the most recently closed tab", "Ctrl+Shift+T"),
            new("browser-ctrl-tab", "浏览器", "Browser", "切换到下一个标签页", "Switch to the next tab", "Ctrl+Tab"),
            new("browser-ctrl-shift-tab", "浏览器", "Browser", "切换到上一个标签页", "Switch to the previous tab", "Ctrl+Shift+Tab"),
            new("ctrl-1", "浏览器", "Browser", "切换到第 1 个标签页", "Switch to the 1st tab", "Ctrl+1"),
            new("ctrl-2", "浏览器", "Browser", "切换到第 2 个标签页", "Switch to the 2nd tab", "Ctrl+2"),
            new("ctrl-3", "浏览器", "Browser", "切换到第 3 个标签页", "Switch to the 3rd tab", "Ctrl+3"),
            new("ctrl-4", "浏览器", "Browser", "切换到第 4 个标签页", "Switch to the 4th tab", "Ctrl+4"),
            new("ctrl-5", "浏览器", "Browser", "切换到第 5 个标签页", "Switch to the 5th tab", "Ctrl+5"),
            new("ctrl-6", "浏览器", "Browser", "切换到第 6 个标签页", "Switch to the 6th tab", "Ctrl+6"),
            new("ctrl-7", "浏览器", "Browser", "切换到第 7 个标签页", "Switch to the 7th tab", "Ctrl+7"),
            new("ctrl-8", "浏览器", "Browser", "切换到第 8 个标签页", "Switch to the 8th tab", "Ctrl+8"),
            new("ctrl-9", "浏览器", "Browser", "切换到最后一个标签页", "Switch to the last tab", "Ctrl+9"),
            new("browser-ctrl-n", "浏览器", "Browser", "打开新的浏览器窗口", "Open a new browser window", "Ctrl+N"),
            new("browser-ctrl-shift-n", "浏览器", "Browser", "打开新的无痕窗口", "Open a new incognito window", "Ctrl+Shift+N"),
            new("browser-ctrl-shift-w", "浏览器", "Browser", "关闭当前浏览器窗口", "Close the current browser window", "Ctrl+Shift+W"),
            new("browser-alt-left", "浏览器", "Browser", "后退到上一个页面", "Go back to the previous page", "Alt+Left"),
            new("browser-alt-right", "浏览器", "Browser", "前进到下一个页面", "Go forward to the next page", "Alt+Right"),
            new("alt-home", "浏览器", "Browser", "打开浏览器主页", "Open the browser home page", "Alt+Home"),
            new("ctrl-r", "浏览器", "Browser", "重新加载页面", "Reload the page", "Ctrl+R"),
            new("browser-f5", "浏览器", "Browser", "刷新页面", "Refresh the page", "F5"),
            new("ctrl-f5", "浏览器", "Browser", "强制刷新页面（忽略缓存）", "Hard refresh the page ignoring the cache", "Ctrl+F5"),
            new("browser-esc", "浏览器", "Browser", "停止加载页面", "Stop loading the page", "Esc"),
            new("ctrl-l", "浏览器", "Browser", "把焦点移到地址栏", "Focus the address bar", "Ctrl+L"),
            new("browser-alt-d", "浏览器", "Browser", "选中地址栏", "Focus the address bar", "Alt+D"),
            new("ctrl-d", "浏览器", "Browser", "把当前页面加入书签", "Bookmark the current page", "Ctrl+D"),
            new("ctrl-shift-d", "浏览器", "Browser", "把所有打开的标签页加入书签", "Bookmark all open tabs", "Ctrl+Shift+D"),
            new("ctrl-shift-o", "浏览器", "Browser", "打开书签管理器", "Open the bookmark manager", "Ctrl+Shift+O"),
            new("ctrl-h", "浏览器", "Browser", "打开历史记录", "Open the history page", "Ctrl+H"),
            new("ctrl-j", "浏览器", "Browser", "打开下载内容", "Open the downloads page", "Ctrl+J"),
            new("ctrl-shift-delete", "浏览器", "Browser", "打开清除浏览数据对话框", "Open the clear browsing data dialog", "Ctrl+Shift+Delete"),
            new("ctrl-p", "浏览器", "Browser", "打印当前页面", "Print the current page", "Ctrl+P"),
            new("ctrl-s", "浏览器", "Browser", "保存当前页面", "Save the current page", "Ctrl+S"),
            new("browser-ctrl-f", "浏览器", "Browser", "在页面上查找", "Find on the page", "Ctrl+F"),
            new("browser-f11", "浏览器", "Browser", "全屏显示", "Toggle full screen", "F11"),
            new("f12", "浏览器", "Browser", "打开开发者工具", "Open developer tools", "F12"),
            new("ctrl-shift-i", "浏览器", "Browser", "打开开发者工具", "Open developer tools", "Ctrl+Shift+I"),
            new("ctrl-shift-j", "浏览器", "Browser", "打开开发者工具控制台", "Open the developer console", "Ctrl+Shift+J"),
            new("ctrl-u", "浏览器", "Browser", "查看网页源代码", "View the page source", "Ctrl+U"),

            // ==== 文本编辑 ====
            new("ctrl-a", "文本编辑", "Text Editing", "全选", "Select all", "Ctrl+A"),
            new("ctrl-c", "文本编辑", "Text Editing", "复制", "Copy", "Ctrl+C"),
            new("ctrl-x", "文本编辑", "Text Editing", "剪切", "Cut", "Ctrl+X"),
            new("ctrl-v", "文本编辑", "Text Editing", "粘贴", "Paste", "Ctrl+V"),
            new("ctrl-z", "文本编辑", "Text Editing", "撤销", "Undo", "Ctrl+Z"),
            new("ctrl-y", "文本编辑", "Text Editing", "重做", "Redo", "Ctrl+Y"),
            new("ctrl-shift-v", "文本编辑", "Text Editing", "粘贴为纯文本", "Paste as plain text", "Ctrl+Shift+V"),
            new("ctrl-insert", "文本编辑", "Text Editing", "复制（IBM 风格）", "Copy (IBM style)", "Ctrl+Insert"),
            new("shift-insert", "文本编辑", "Text Editing", "粘贴（IBM 风格）", "Paste (IBM style)", "Shift+Insert"),
            new("backspace", "文本编辑", "Text Editing", "删除光标前的字符", "Delete the character before the cursor", "Backspace"),
            new("delete", "文本编辑", "Text Editing", "删除光标后的字符", "Delete the character after the cursor", "Delete"),
            new("ctrl-backspace", "文本编辑", "Text Editing", "删除光标前的一个词", "Delete the previous word", "Ctrl+Backspace"),
            new("ctrl-delete", "文本编辑", "Text Editing", "删除光标后的一个词", "Delete the next word", "Ctrl+Delete"),
            new("insert", "文本编辑", "Text Editing", "切换插入与改写模式", "Toggle insert and overwrite mode", "Insert"),
            new("home", "文本编辑", "Text Editing", "移到行首", "Move to the start of the line", "Home"),
            new("end", "文本编辑", "Text Editing", "移到行尾", "Move to the end of the line", "End"),
            new("ctrl-home", "文本编辑", "Text Editing", "移到文档开头", "Move to the start of the document", "Ctrl+Home"),
            new("ctrl-end", "文本编辑", "Text Editing", "移到文档末尾", "Move to the end of the document", "Ctrl+End"),
            new("pageup", "文本编辑", "Text Editing", "向上翻页", "Scroll up one page", "PageUp"),
            new("pagedown", "文本编辑", "Text Editing", "向下翻页", "Scroll down one page", "PageDown"),
            new("left", "文本编辑", "Text Editing", "光标左移一个字符", "Move the cursor left one character", "Left"),
            new("right", "文本编辑", "Text Editing", "光标右移一个字符", "Move the cursor right one character", "Right"),
            new("up", "文本编辑", "Text Editing", "光标上移一行", "Move the cursor up one line", "Up"),
            new("down", "文本编辑", "Text Editing", "光标下移一行", "Move the cursor down one line", "Down"),
            new("ctrl-left", "文本编辑", "Text Editing", "光标左移一个词", "Move the cursor left one word", "Ctrl+Left"),
            new("ctrl-right", "文本编辑", "Text Editing", "光标右移一个词", "Move the cursor right one word", "Ctrl+Right"),
            new("ctrl-up", "文本编辑", "Text Editing", "光标上移一段", "Move the cursor up one paragraph", "Ctrl+Up"),
            new("ctrl-down", "文本编辑", "Text Editing", "光标下移一段", "Move the cursor down one paragraph", "Ctrl+Down"),
            new("shift-left", "文本编辑", "Text Editing", "向左选中一个字符", "Extend the selection left by one character", "Shift+Left"),
            new("shift-right", "文本编辑", "Text Editing", "向右选中一个字符", "Extend the selection right by one character", "Shift+Right"),
            new("shift-up", "文本编辑", "Text Editing", "向上选中一行", "Extend the selection up one line", "Shift+Up"),
            new("shift-down", "文本编辑", "Text Editing", "向下选中一行", "Extend the selection down one line", "Shift+Down"),
            new("shift-home", "文本编辑", "Text Editing", "选中到行首", "Extend the selection to the start of the line", "Shift+Home"),
            new("shift-end", "文本编辑", "Text Editing", "选中到行尾", "Extend the selection to the end of the line", "Shift+End"),
            new("ctrl-shift-left", "文本编辑", "Text Editing", "按词向左扩展选区", "Extend the selection left by one word", "Ctrl+Shift+Left"),
            new("ctrl-shift-right", "文本编辑", "Text Editing", "按词向右扩展选区", "Extend the selection right by one word", "Ctrl+Shift+Right"),
            new("ctrl-shift-home", "文本编辑", "Text Editing", "选中到文档开头", "Extend the selection to the start of the document", "Ctrl+Shift+Home"),
            new("ctrl-shift-end", "文本编辑", "Text Editing", "选中到文档末尾", "Extend the selection to the end of the document", "Ctrl+Shift+End"),

            // ==== 截图与录屏 ====
            new("win-shift-s", "截图与录屏", "Screenshot & Recording", "打开截图工具栏进行区域截图", "Open the snipping bar to capture a region", "Win+Shift+S"),
            new("win-printscreen", "截图与录屏", "Screenshot & Recording", "截取全屏并自动保存到图片文件夹", "Capture the full screen and save it automatically", "Win+PrintScreen"),
            new("alt-printscreen", "截图与录屏", "Screenshot & Recording", "截取当前窗口到剪贴板", "Copy the active window to the clipboard", "Alt+PrintScreen"),
            new("printscreen", "截图与录屏", "Screenshot & Recording", "截取全屏到剪贴板", "Copy the full screen to the clipboard", "PrintScreen"),

            // ==== 电源 ====
            new("win-x", "电源", "Power", "打开快速链接菜单（含关机与重启）", "Open the Quick Link menu with power options", "Win+X"),
            new("ctrl-alt-delete", "电源", "Power", "打开安全选项界面", "Open the security options screen", "Ctrl+Alt+Delete"),
            new("win-ctrl-shift-b", "电源", "Power", "重置显卡驱动（黑屏时恢复显示）", "Reset the graphics driver", "Win+Ctrl+Shift+B"),
            new("win-l", "电源", "Power", "锁定计算机", "Lock the computer", "Win+L"),

            // ==== 对话框 ====
            new("tab", "对话框", "Dialogs", "在对话框控件之间移动焦点", "Move focus between dialog controls", "Tab"),
            new("shift-tab", "对话框", "Dialogs", "反向移动焦点", "Move focus backwards", "Shift+Tab"),
            new("dialog-ctrl-tab", "对话框", "Dialogs", "切换到对话框的下一个选项卡", "Switch to the next tab in a dialog", "Ctrl+Tab"),
            new("dialog-ctrl-shift-tab", "对话框", "Dialogs", "切换到对话框的上一个选项卡", "Switch to the previous tab in a dialog", "Ctrl+Shift+Tab"),
            new("enter", "对话框", "Dialogs", "激活默认按钮", "Activate the default button", "Enter"),
            new("dialog-esc", "对话框", "Dialogs", "取消或关闭对话框", "Cancel or close the dialog", "Esc"),
            new("space", "对话框", "Dialogs", "选中或取消选中复选框", "Select or clear a check box", "Space"),
            new("alt-space", "对话框", "Dialogs", "打开窗口的系统菜单", "Open the window system menu", "Alt+Space"),
            new("shift-f10", "对话框", "Dialogs", "打开所选项目的右键菜单", "Open the context menu for the selection", "Shift+F10"),
            new("dialog-f4", "对话框", "Dialogs", "打开下拉列表", "Open a drop-down list", "F4"),
            new("dialog-alt-f", "对话框", "Dialogs", "打开“文件”菜单", "Open the File menu", "Alt+F"),
            new("dialog-alt-e", "对话框", "Dialogs", "打开“编辑”菜单", "Open the Edit menu", "Alt+E"),
            new("dialog-alt-v", "对话框", "Dialogs", "打开“视图”菜单", "Open the View menu", "Alt+V"),
            new("dialog-alt-h", "对话框", "Dialogs", "打开“帮助”菜单", "Open the Help menu", "Alt+H"),

            // ==== 游戏栏 ====
            new("win-g", "游戏栏", "Game Bar", "打开 Xbox Game Bar", "Open Xbox Game Bar", "Win+G"),
            new("win-alt-g", "游戏栏", "Game Bar", "打开捕获小组件", "Open the capture widget", "Win+Alt+G"),
            new("win-alt-r", "游戏栏", "Game Bar", "开始或停止录制", "Start or stop recording", "Win+Alt+R"),
            new("win-alt-printscreen", "游戏栏", "Game Bar", "截取游戏截图", "Take a game screenshot", "Win+Alt+PrintScreen"),
            new("win-alt-m", "游戏栏", "Game Bar", "打开或关闭麦克风", "Turn the microphone on or off", "Win+Alt+M"),
            new("win-alt-b", "游戏栏", "Game Bar", "打开或关闭 HDR", "Turn HDR on or off", "Win+Alt+B"),
            new("win-alt-t", "游戏栏", "Game Bar", "显示或隐藏录制计时器", "Show or hide the recording timer", "Win+Alt+T"),

            // ==== 输入法 ====
            new("win-space", "输入法", "Input", "切换输入法与键盘布局", "Switch the input method and keyboard layout", "Win+Space"),
            new("ctrl-space", "输入法", "Input", "切换中英文输入（经典快捷键）", "Toggle the IME on or off", "Ctrl+Space"),
            new("alt-shift", "输入法", "Input", "切换输入语言", "Switch the input language", "Alt+Shift"),
            new("ctrl-shift", "输入法", "Input", "切换键盘布局", "Switch the keyboard layout", "Ctrl+Shift"),
            new("win-slash", "输入法", "Input", "触发输入法转换 / 重转换", "Start IME reconversion", "Win+/")
        };
    }
}
